[package]
name = "htmd"
version = "0.1.2"
edition = "2021"
authors = ["letmutex"]
description = "A turndown.js inspired HTML to Markdown converter."
license = "Apache-2.0"
repository = "https://github.com/letmutex/htmd"
homepage = "https://github.com/letmutex/htmd"
keywords = ["html", "markdown", "converter"]
categories = ["text-processing", "parsing"]
readme = "README.md"

[dependencies]
html5ever = "0.27"
markup5ever_rcdom = "0.3.0"

[dev-dependencies]
scraper = "0.19.0"
